# GitHub Sponsors funding file
# This is a learning project and currently free to use
# If you'd like to support future development, consider:
# - Starring the repository
# - Contributing code or documentation
# - Sharing with others who might find it useful

github: [CuWilliams]
